# Generated by Django 5.0 on 2024-01-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendingMachine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(),
        ),
    ]
