# Generated by Django 5.0 on 2023-12-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinationPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("day_wise", models.JSONField()),
            ],
        ),
    ]
