# Generated by Django 5.0 on 2023-12-25 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travelo", "0002_destinationpackage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DestinationPackage",
            new_name="Package",
        ),
    ]
