# Generated by Django 5.0 on 2023-12-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelo", "0003_rename_destinationpackage_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="destination",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="travelo.destination",
            ),
            preserve_default=False,
        ),
    ]
