# Generated by Django 5.0 on 2023-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelo", "0004_package_destination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="destination",
        ),
        migrations.AddField(
            model_name="package",
            name="description_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
